# Configuration file for this token refresh tool.
#
# URL for Aruba Centarl APIs
# US-1: https://app1-apigw.central.arubanetworks.com
# US-2: https://apigw-prod2.central.arubanetworks.com
# CAN-1: https://apigw-ca.central.arubanetworks.com
#
# The URL, customer_id, client_id, client_secret for your account will be listed under the 
# Maintenance > API Gateway within your Aruba Central
# account.
#
# 
#

# Base token file name. 
tokenfile:  token.json


default:
  url: https://apigw-prod2.central.arubanetworks.com
  envapi:  prod
  customer_id: enter_customer_id
  client_id: enter_client_id
  client_secret: enter_client_secret


#
# Enter multiple accounts 
#
# AccountName:
#   url: https://apigw-prod2.central.arubanetworks.com
#   envapi:  prod
#   customer_id: 1234567...
#   client_id: 34567...
#   client_secret: 9876543...
